export const DISPOSABLE_DOMAINS = new Set([
  // Common disposable email providers
  'mailinator.com', 'guerrillamail.com', 'tempmail.com', 'throwaway.email',
  'yopmail.com', 'sharklasers.com', 'guerrillamailblock.com', 'grr.la',
  'guerrillamail.info', 'spam4.me', 'trashmail.com', 'trashmail.me',
  'dispostable.com', 'maildrop.cc', 'fakeinbox.com', 'mailnull.com',
  'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org', 'spamspot.com',
  'spamthis.co.uk', 'tempinbox.com', 'tempr.email', 'discard.email',
  'mailnesia.com', 'spamfree24.org', '10minutemail.com', 'temp-mail.org',
  'mailcatch.com', 'mailpoof.com', 'mohmal.com', 'mailinator.org',
  'mailinator.net', 'mailinator.info', 'mailinator.biz', 'mailinator.co',
  'mailinator.us', 'mailinator.uk', 'mailinator.eu', 'mailinator.asia',
  'mailinator.tv', 'mailinator.ws', 'mailinator.mobi', 'mailinator.name',
  'mailinator.me', 'mailinator.io', 'mailinator.co', 'mailinator.app',
  'guerrillamail.de', 'guerrillamail.biz', 'guerrillamail.net',
  'guerrillamail.org', 'guerrillamail.co', 'sharklasers.com', 'spam4.me',
  'dontreg.com', 'getairmail.com', 'gishpuppy.com', 'hotpop.com',
  'inboxalias.com', 'joelpet.com', 'kasmail.com', 'mail2web.com',
  'mailinator.com', 'mailmetrash.com', 'mailmoat.com', 'mailzilla.org',
  'mintemail.com', 'mytrashmail.com', 'nepwk.com', 'nobugmail.com',
  'nospam4.us', 'nospamfor.us', 'nowmymail.com', 'pookmail.com',
  'proxymail.eu', 'rcpt.at', 'safersignup.de', 'safetymail.info',
  'safetypost.de', 'sandelf.de', 'selfdestructingmail.com', 'sendspamhere.com',
  'shitmail.me', 'skeefmail.com', 'slopsbox.com', 'smellfear.com',
  'snakemail.com', 'sofort-mail.de', 'sogetthis.com', 'spam.la',
  'spam.su', 'spamavert.com', 'spambob.com', 'spambob.net', 'spambob.org',
  'spambox.info', 'spambox.irishspringrealty.com', 'spambox.us', 'spamcannon.com',
  'spamcannon.net', 'spamcannon.org', 'spamday.com', 'spamfree24.com',
  'spamfree24.de', 'spamfree24.eu', 'spamfree24.info', 'spamfree24.net',
  'spamfree24.org', 'spamgoes.in', 'spamherelots.com', 'spamhereplease.com',
  'spamhole.com', 'spamhole.nu', 'spamify.com', 'spaminator.de',
  'spamkill.info', 'spaml.com', 'spaml.de', 'spammotel.com', 'spamobox.com',
  'spamoff.de', 'spamsphere.com', 'spamspot.com', 'spamthis.co.uk',
  'spamthisplease.com', 'speed.1s.fr', 'sr.ro', 'superstachel.de',
  'temp-mail.com', 'temp-mail.de', 'temp-mail.org', 'temp-mail.ru',
  'tempemail.co.za', 'tempemail.net', 'tempinbox.co', 'tempinbox.com',
  'tempmail.de', 'tempmail.eu', 'tempmail.it', 'tempmail.org',
  'tempmail.pp.ua', 'tempmail.us', 'tempmailer.com', 'tempmailer.de',
  'tempomail.fr', 'temporarily.de', 'temporaryemail.net', 'temporaryforwarding.com',
  'temporarymailaddress.com', 'tempsmtp.com', 'thankyou2010.com', 'thismail.net',
  'throwaway.email', 'throwawayemailaddress.com', 'trash-amil.com', 'trash-mail.at',
  'trash-mail.cf', 'trash-mail.ga', 'trash-mail.gq', 'trash-mail.ml',
  'trash-mail.tk', 'trash2009.com', 'trashemail.de', 'trashmail.com',
  'trashmail.de', 'trashmail.me', 'trashmail.net', 'trashmail.org',
  'trashmail.ws', 'trashymail.com', 'trashymail.net', 'trillianpro.com',
  'tyldd.com', 'uggsrock.com', 'upliftnow.com', 'veryrealemail.com',
  'viditag.com', 'vipmail.pw', 'vomoto.com', 'walala.org', 'walkmail.ru',
  'wasteland.rfc822.org', 'webemail.me', 'webtrip.ch', 'wegwerfadresse.de',
  'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'whatiaas.com', 'whyspam.me', 'wibblesmith.com', 'wimsg.com', 'winemaven.info',
  'wronghead.com', 'wuzup.net', 'wuzupmail.net', 'xagloo.com', 'xmail.com',
  'yep.it', 'yogamaven.com', 'yopmail.com', 'yopmail.fr', 'yopmail.gq',
  'yopmail.net', 'ypmail.webarnak.fr.eu.org', 'zehnminuten.de', 'zippymail.info',
  'zoemail.com', 'zoemail.net', 'zoemail.org', 'zoetropes.org',
  'zomg.info', 'zxcv.com', 'zzz.com',
]);
